spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cofeeshop?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: "root"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#  mvc
#    hiddenmethod
#      filter
#        enabled: true

###Logging Levels
# Disable the default loggers
#logging:
#  level:
#    org.hibernate: DEBUG
#server:
#  port : 8081